FROM registry.access.redhat.com/ubi9/python-311

USER root
WORKDIR /app/

RUN dnf update -y

RUN pip3 install uv
COPY pyproject.toml pyproject.toml
RUN uv pip install -r pyproject.toml

COPY . .
RUN chmod -R +r . && ls -la

EXPOSE 8000
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
